@hostname = localhost
@port = 5101
@host = https://{{hostname}}:{{port}}
@ContentType = application/json 

###
GET {{host}}/api/users

###
GET {{host}}/api/users/1

###
DELETE {{host}}/api/users/0

###
POST {{host}}/api/users
Content-Type: {{{{ContentType}}

"Bob Builder"

###
PUT {{host}}/api/users/1
Content-Type: {{ContentType}}

"Justin Time"