# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Deploy

on:
  push:
    branches:
      - Assignment*

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./SecretSanta/src/SecretSanta.Web

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
        
    - name: npm install
      run: npm install
      
    - name: npm build
      run: npm run build:prod

    - name: (WEB) Build with dotnet
      run: dotnet build --configuration Release

    - name: (WEB) dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/binSecretSanta

    - name: (API) Build with dotnet
      working-directory: ./SecretSanta/src/SecretSanta.Api
      run: dotnet build --configuration Release

    - name: (API) dotnet publish
      working-directory: ./SecretSanta/src/SecretSanta.Api
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/apiSecretSanta

    - name: Run Azure webapp deploy API using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: jmplettSecretSanta-API
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4E6987F84DD846A5B94D86FBD4CB89C7 }}
        package: ${{env.DOTNET_ROOT}}/apiSecretSanta

    - name: Run Azure webapp deploy WEB using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: jmplettSecretSanta
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_285CF45FD2184C7C8285E4875494877E }}
        package: ${{env.DOTNET_ROOT}}/binSecretSanta
