name: BuildAndTest

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ Assignment6 ]
  pull_request:
    branches: [ Assignment6 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    defaults:
      run:
        working-directory: ./SecretSanta/
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
          
      - name: Run npm
        working-directory: ./SecretSanta/src/SecretSanta.Web/
        run: |
          npm install
          npm run build:prod
      
      - name: Build
        run: dotnet build
        
      - name: debug directory for tests
        run: pwd

      - name: Test
        run: dotnet test --no-build
